<?php

namespace Fenchy\NoticeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;

use Fenchy\UserBundle\Entity\User;
use Fenchy\RegularUserBundle\Entity\UserGroup;
use Symfony\Bundle\AsseticBundle\Factory\Worker\UseControllerWorker;
/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestRepository extends EntityRepository
{
        public function getFullDetailedList ($filter = NULL) {

            if(!($filter instanceof \Fenchy\AdminBundle\Entity\RequestsFilter)) {

                return $this->createQueryBuilder('r')
                        ->select('r, a, n, u')
                        ->join('r.author', 'a')
                        ->leftJoin('r.aboutNotice', 'n')
                        ->leftJoin('r.aboutUser', 'u')
                        ->leftJoin('r.aboutUserGroup', 'ug')                        
                        ->getQuery()
                        ->getResult();
            } 

           

            $query = $this->createQueryBuilder('r')
                        ->select('r, a')
                        ->join('r.author', 'a');
            $query->join('r.aboutUser', 'u');


           

             if($filter->text) {
                $query->where('LOWER(r.text) like :text')
                        ->setParameter('text', strtolower('%'.$filter->text.'%'));
            }

            if($filter->author) {
                $query->andWhere('LOWER(a.email) like :email')
                        ->setParameter('email', strtolower('%'.$filter->author.'%'));
            }

            if($filter->receiver) {               
                $query->andWhere('LOWER(u.email) like :email1')
                        ->setParameter('email1', strtolower('%'.$filter->receiver.'%'));
            }

            if($filter->target === 'user') {
                $query->addSelect('u');

            } elseif($filter->target === 'notice') {
                $query->join('r.aboutNotice', 'n')
                        ->addSelect('n');
            }




            if($filter->sort === 'stickersQ') {
                return $query
                        ->orderBy($filter->sort, $filter->order)
                        ->getQuery()
                        ->getResult();
            }
            if($filter->sort === 'receiver') {
                return $query
                        ->orderBy('r.aboutUser', $filter->order)
                        ->getQuery()
                        ->getResult();
            }

            return $query
                        ->orderBy('r.'.$filter->sort, $filter->order)
                        ->getQuery()
                        ->getResult();
        }
	public function findByInJSON($router, array $criteria, array $orderBy, $limit, $offset) {
		$requests = $this->findBy($criteria,$orderBy,$limit,$offset);
		$requestsJSON = array();

		foreach($requests as $oneRequest) {

			$author = $oneRequest->getAuthor();
			$authorProfileUrl = $router->generate(
					'fenchy_regular_user_user_otherprofile_aboutotherchoice',
					array('userId' => $author->getId()) );

			$aboutUser = $oneRequest->getAboutUser();
			$aboutUserProfileUrl = $router->generate(
					'fenchy_regular_user_user_profilev2',
					array('userId' => $aboutUser->getId()) );

			$aboutNotice = $oneRequest->getAboutNotice();
			//echo "<pre>"; print_r($aboutNotice);exit;

			$hasNotice = ( $aboutNotice && $aboutNotice->getId() );
			if ( $hasNotice ) {
				$aboutNoticeUrl = $router
				->generate('fenchy_notice_show_slug', array(
						'slug' => $aboutNotice->getSlug(),
						'year' => $aboutNotice->getCreatedAt()->format('Y'),
						'month' => $aboutNotice->getCreatedAt()->format('m'),
						'day' => $aboutNotice->getCreatedAt()->format('d') ));
			}

			$requestsJSON[] = array(
					'author'=>array(
							'id' => $author->getId(),
							'name' => $author->getUserRegular()->getFirstname(),
							'image' =>  $author->getUserRegular()->getAvatar(),
							'profileUrl' => $authorProfileUrl,
							'activity' => $author->getActivity()
					),
					'aboutuser' => array(
							'id' => $aboutUser->getId(),
							'name' => $aboutUser->getUserRegular()->getFirstname(),
							'image' => $aboutUser->getUserRegular()->getAvatar(),
							'profileUrl' => $aboutUserProfileUrl
					),
					'aboutnotice' => $hasNotice ? array(
							'id' => $aboutNotice->getId(),
							'title' => $aboutNotice->getTitle(),
							'image' => '',
							'noticeUrl' => $aboutNoticeUrl,
							'completed' => $aboutNotice->getCompleted(),
							'type' => $aboutNotice->getType()
					) : null,
					'id' => $oneRequest->getId(),
					'status' => $oneRequest->getStatus(),
					'requeststatus' => $oneRequest->getRequeststatus(),
					'text' => $oneRequest->getText(),
					'title' => $oneRequest->getTitle(),
					'createdAt'=> $oneRequest->getCreatedAt(),
					'piece_spot' => $oneRequest->getPieceSpot(),
					'price' => $oneRequest->getPrice(),
					'free' => $oneRequest->getFree(),
					'proposeprice' => $oneRequest->getProposeprice(),
					'totalprice' => $oneRequest->getTotalprice(),
					'currency' => $oneRequest->getCurrency(),
					'is_read' => $oneRequest->getIsRead(),
					'is_read_status' => $oneRequest->getIsReadStatus(),
					'start_date'=> $oneRequest->getStartDate(),
					'end_date' => $oneRequest->getEndDate(),
					'start_time' => $oneRequest->getStartTime(),
					'end_time' => $oneRequest->getEndTime(),
                                        'blue'=> $oneRequest->getBlue(),
                                        'req_blue' => $oneRequest->getRequestBlue(),
                                        'my_review' => $oneRequest->getMyReview(),
                                        'other_review' => $oneRequest->getOtherReview(),
                                        'swap_msg' => $oneRequest->getSwapMsg(),
                                        'proposed_location' => $oneRequest->getProposedLocation()
			);
		}

		return $requestsJSON;
	}

	/**
	 * Set the flag `is_read` on user's requests
	 * @param boolean $is_read_state
	 * @param \Fenchy\UserBundle\Entity\User $user
	 * @author Mateusz Krowiak <mkrowiak@pgs-soft.com>
	 */
	public function updateUsersRequestsWithIsRead($is_read_state, User $user) {

		$is_read_state = $is_read_state?'true':'false';

		$query = $this->createQueryBuilder('r')
		->update()
		->set('r.is_read', $is_read_state)
		->where('r.aboutUser = :user')
		->getQuery();

		$query->setParameter('user', $user);

		return $query->execute();

	}
        public function updateNeighborMsgBlueReadStatus($noticeId, $flag, $requestId)
        {
            if(!$requestId && $flag=='true')
            {
                    $query = $this->createQueryBuilder('r')
                        ->update()
                        ->set('r.request_blue', 'true')
                        ->where('r.aboutNeighborhoodMsg = :aboutNeighborhoodMsg')
                        ->getQuery();
            }
            else if($flag == 'false')
            {
                $query = $this->createQueryBuilder('r')
                    ->update()
                    ->set('r.blue', 'true')
                    ->where('r.aboutNeighborhoodMsg = :aboutNeighborhoodMsg')
                    ->getQuery();
            }
            $query->setParameter('aboutNeighborhoodMsg',$noticeId);

		return $query->execute();
        }
        
        public function updateBlueReadStatus($noticeId, $flag, $requestId)
        {
            if($requestId && $flag=='true')
            {
                
                    $query = $this->createQueryBuilder('r')
                        ->update()
                        ->set('r.blue', 'true')
                        ->where('r.id = :request')
                        ->setParameter('request',$requestId)
                        ->getQuery();
                     

		return $query->execute();
            }
            else if($requestId)
            {
                    $query = $this->createQueryBuilder('r')
                        ->update()
                        ->set('r.request_blue', 'true')
                        ->where('r.id = :request')
                        ->setParameter('request',$requestId)
                        ->getQuery();
                     

		return $query->execute();
            }
            
            if(!$requestId && $flag=='true')
            {
                    $query = $this->createQueryBuilder('r')
                        ->update()
                        ->set('r.request_blue', 'true')
                        ->where('r.aboutNotice = :notice')
                        ->getQuery();
            }
            else if($flag == 'false')
            {
                $query = $this->createQueryBuilder('r')
                    ->update()
                    ->set('r.blue', 'true')
                    ->where('r.aboutNotice = :notice')
                    ->getQuery();
            }
            $query->setParameter('notice',$noticeId);

		return $query->execute();
        }

        /**
	 *
	 * Return number of unread User's requests
	 * @return integer
	 * @param \Fenchy\UserBundle\Entity\User $user
	 */
	public function countUnreadUsersRequests(User $user, $listings=NULL) {

		if($listings)
		{
			$query = $this->createQueryBuilder('r')
			->select('COUNT(r.id)')
			->where('r.is_read = :read and r.aboutUser = :user and r.aboutNotice IS NOT NULL and r.aboutNotice NOT IN(:listings)' )
			->setParameters(array(
					'read' => 'false',
					'user' => $user,
					'listings'=> array_values($listings)
			))
			->getQuery();
		}
		else 
		{
			$query = $this->createQueryBuilder('r')
			->select('COUNT(r.id)')
			->where('r.is_read = :read and r.aboutUser = :user and r.aboutNotice IS NOT NULL')
			->setParameters(array(
					'read' => 'false',
					'user' => $user
			))
			->getQuery();
		}
                
                        $query1 = $this->createQueryBuilder('r')
			->select('COUNT(r.id)')
			->where('r.is_read = :read and r.aboutUser = :user and r.aboutNotice IS NULL')
			->setParameters(array(
					'read' => 'false',
					'user' => $user
			))
			->getQuery();
                        
		$total = $query->getSingleScalarResult() + $query1->getSingleScalarResult();
		return $total;

	}
	
	public function countUnreadUsersRequestsInGroup($groupId) {
	
	        $query1 = $this->createQueryBuilder('r')
			->select('COUNT(r.id)')
			->where('r.is_read = :read and r.aboutUserGroup = :group')
			->setParameters(array(
                                        'read' => 'false',
					'group' => $groupId		
			))
			->getQuery();
                        
                return  $query1->getSingleScalarResult();
		
	
	}
        public function updateGroupRequestReadStatus($groupId)
        {
              $query = $this->createQueryBuilder('r')
                        ->update()
                        ->set('r.is_read', 'true')
                        ->where('r.aboutUserGroup = :group')
                        ->setParameter('group', $groupId)
                        ->getQuery();                     

		return $query->execute();
        }
	public function countUnreadUsersStatusRequests(User $user, $listings) {
	
		if($listings)
		{		
			$query = $this->createQueryBuilder('r')
			->select('COUNT(r.id)')
			->where('r.is_read_status = :read and r.author = :user and r.aboutNotice IS NOT NULL and r.aboutNotice NOT IN(:listings)')
			->setParameters(array(
					'read' => 'false',
					'user' => $user,
					'listings'=> array_values($listings)
			))
			->getQuery();
		}
		else 
		{
			$query = $this->createQueryBuilder('r')
			->select('COUNT(r.id)')
			->where('r.is_read_status = :read and r.author = :user and r.aboutNotice IS NOT NULL')
			->setParameters(array(
					'read' => 'false',
					'user' => $user,					
			))
			->getQuery();
		}
	
                $query1 = $this->createQueryBuilder('r')
			->select('COUNT(r.id)')
			->where('r.is_read_status = :read and r.author = :user and r.aboutNotice IS NULL')
			->setParameters(array(
					'read' => 'false',
					'user' => $user
			))
			->getQuery();
                
		$total = $query->getSingleScalarResult()+ $query1->getSingleScalarResult();
		return $total;
	
	}
	
	public function countUnreadUsersStatusRequestsInGroup($notices) {
	
		$total = 0;
		foreach($notices as $notice)
		{	
			$query = $this->createQueryBuilder('r')
			->select('COUNT(r.id)')
			->where('r.is_read = :read and r.aboutNotice = :notice')
			->setParameters(array(
					'read' => 'false',
					'notice' => $notice
			))
			->getQuery();
	
			$total += $query->getSingleScalarResult();
		}
		
		return $total;
	}
	
	public function countUnreadUsersStatusGroupRequests(User $user,$groupId) {
	
		$query = $this->createQueryBuilder('r')
		->select('COUNT(r.id)')
		->where('r.is_read_status = :read and r.author = :user')
		->setParameters(array(
				'read' => 'false',
				'user' => $user
		))
		->getQuery();
	
		$total = $query->getSingleScalarResult();
		
		return $total;
	
	}
	public function findCount( $criteria ) {
		$query =  $this->createQueryBuilder('r')
		->select('COUNT(r.id)');

		if ( array_key_exists('aboutUser', $criteria) ) {
			$query->andWhere('r.aboutUser = '.$criteria['aboutUser']);
		}

		if ( array_key_exists('author', $criteria) ) {
			$query->andWhere('r.author = '.$criteria['author']);
		}

		if ( array_key_exists('aboutNotice', $criteria) ) {
			$query->andWhere('r.aboutNotice = '.$criteria['aboutNotice']);
		}

		if ( array_key_exists('type', $criteria) ) {
			$query->andWhere('r.type = '.$criteria['type']);
		}

		return $query->getQuery()->getSingleScalarResult();
	}
	
	public function getNoticeIds(User $user)
	{
		return  $this->createQueryBuilder('r')
				->select('r')				
				->andWhere('r.author = :author')
                                //->andWhere('r.aboutUserGroup IS NULL')
                                ->setParameter('author', $user->getId())
                                ->getQuery()
				->getResult();
	}
	
	public function getRequests(User $user)
	{
		return  $this->createQueryBuilder('r')
		->select('r')
		->andWhere('r.author = :author')		
		->andWhere('r.aboutUserGroup IS NULL')
                ->setParameter('author', $user->getId())
                ->getQuery()
		->getResult();
	}
        
        public function getRequestsToUserGroup(User $user)
	{
		return  $this->createQueryBuilder('r')
		->select('r')
		->andWhere('r.author = :author')		
		->andWhere('r.aboutUserGroup IS NOT NULL')
                ->andWhere('r.aboutNotice IS NULL')
                ->setParameter('author', $user->getId())
                ->getQuery()
		->getResult();
	}
	
	public function getGroupNoticeIds(User $user)
	{
		return  $this->createQueryBuilder('r')
				->select('r')
				->where('r.author = :author')
				->setParameter('author', $user->getId())
				->getQuery()
				->getResult();
	}
	
	public function getSingleNeighbourRequeste(User $user, User $aboutuser)
	{
		return  $this->createQueryBuilder('r')
				->select('r')
				->where('r.author = :author and r.aboutUser = :aboutuser')
				->setParameter('author', $user->getId())
				->setParameter('aboutuser', $aboutuser->getId())
				->getQuery()
				->getResult();
	}
        
        public function getSingleUserGroupRequests(User $user, UserGroup $aboutusergroup)
	{
		return  $this->createQueryBuilder('r')
				->select('r')
				->where('r.author = :author and r.aboutUserGroup = :aboutusergroup')
				->setParameter('author', $user->getId())
				->setParameter('aboutusergroup', $aboutusergroup->getId())
				->getQuery()
				->getResult();
	}
	
	public function getNeighboursRequests(User $user)
	{
		return  $this->createQueryBuilder('r')
				->select('r')
				->andWhere('r.aboutUser = :aboutuser')
                                ->andWhere('r.aboutNeighborhoodMsg IS NULL')
				->setParameter('aboutuser', $user->getId())
				->getQuery()
				->getResult();
	}
        
        public function getNeighbourhoodMsgRequests(User $user)
	{
		return  $this->createQueryBuilder('r')
				->select('r')
				->andWhere('r.aboutUser = :aboutuser')
                                ->andWhere('r.aboutNeighborhoodMsg IS NOT NULL')
				->setParameter('aboutuser', $user->getId())
				->getQuery()
				->getResult();
	}
        
        public function getJoinClosedGroupsRequestsForMember(User $user)
	{
		return  $this->createQueryBuilder('r')
				->select('r')
				->where('r.author = :author and r.aboutUserGroup IS NOT NULL')
				->setParameter('author', $user->getId())
				->getQuery()
				->getResult();
	}
        
        public function getJoinClosedGroupsRequests(UserGroup $usergroup)
	{
		return  $this->createQueryBuilder('r')
				->select('r')
				->where('r.aboutUserGroup = :aboutusergroup')
				->setParameter('aboutusergroup', $usergroup->getId())
				->getQuery()
				->getResult();
	}
	
	public function countUsersDoneRequest(User $user) {
	
		$query = $this->createQueryBuilder('r')
		->select('COUNT(r.id)')
		->where('r.requeststatus = :done and r.aboutUser = :user')
		->setParameters(array(
				'done' => 'done',
				'user' => $user
		))
		->getQuery();
	
		$total = $query->getSingleScalarResult();
		return $total;
	
	}
	
	public function countMyRequestMarkAsDone(User $user) {
	
		$query = $this->createQueryBuilder('r')
		->select('COUNT(r.id)')
		->where('r.requeststatus = :done and r.author = :user')
		->setParameters(array(
				'done' => 'done',
				'user' => $user
		))
		->getQuery();
	
		$total = $query->getSingleScalarResult();
		return $total;
	}
        
        public function getUserRequest(User $user, $notice)
	{
		return  $this->createQueryBuilder('r')
				->select('r')
				->where('r.author = :author and r.aboutNotice = :notice')
				->setParameter('author', $user->getId())
				->setParameter('notice', $notice)
				->getQuery()
				->getOneOrNullResult();
	}
        
        public function getOneRequest(User $user, User $author)
	{
		return  $this->createQueryBuilder('r')
				->select('r')
				->where('r.author = :author and r.aboutUser = :user and r.aboutNotice IS NULL')
                                ->orWhere('r.author = :user and r.aboutUser = :author and r.aboutNotice IS NULL')
				->setParameter('author', $author->getId())
				->setParameter('user', $user->getId())
				->getQuery()
				->getOneOrNullResult();
	}
}