<?php

namespace Fenchy\RegularUserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    /**
     * Counts documents
     * 
     * @param int $user_id
     * @return integer 
     */
    public function findById($user_id)
    {
        return $this->createQueryBuilder('d')
                    ->where('d.user_id = :user_id')
    				->setParameter('user_id', $user_id)
    				->getQuery()
    				->getOneOrNullResult();
    }
}
