<?php

namespace Fenchy\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupPaymentRepository extends EntityRepository
{
	
}
