<?php

namespace Fenchy\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
	public function checkUser(User $user)
	{
		return  $this->createQueryBuilder('p')
				->where('p.user = :user')
				->setParameter('user', $user->getId())
				->getQuery()
				->getOneOrNullResult();
	}
}
