parameters:
#    fenchy_regular_user.example.class: Fenchy\NoticeBundle\Example
# src/Fenchy/NoticeBundle/Resources/config/validation.yml
Fenchy\NoticeBundle\Entity\Value:
    properties:
        value:
          min: 0
          min_error: Please select at least one
          max: 1