<?php

namespace Fenchy\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Fenchy\UserBundle\Entity\User;

/**
 * TellFriendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TellFriendRepository extends EntityRepository
{
    public function checkFacebookIdExist($facebookId, User $user)
    {
        return  $this->createQueryBuilder('tf')
                    ->where('tf.facebook_id = :facebokId')
                    ->andWhere('tf.user = :user')
                    ->setParameter('facebokId', $facebookId)
                    ->setParameter('user', $user->getId())
                    ->getQuery()
                    ->getOneOrNullResult();
        
    }
    
    public function getPoint(User $user)
    {        
        $total =  $this->createQueryBuilder('tf')
                    ->select('COUNT(tf.id)')
                    ->where('tf.by_email = true')
                    ->andWhere('tf.user = :user')
                    ->setParameter('user', $user->getId())
                    ->getQuery()
                    ->getSingleScalarResult();
        
        $facebookResult = $this->createQueryBuilder('tf')
                    ->select('COUNT(tf.id)')
                    ->where('tf.by_email = false')
                    ->andWhere('tf.user = :user')
                    ->setParameter('user', $user->getId())
                    ->getQuery()
                    ->getSingleScalarResult();
        
        $total += intval($facebookResult/2);
        return $total;
    }
}
