<?php

namespace Fenchy\RegularUserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupMembersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupMembersRepository extends EntityRepository
{
	
	/**
	 * Counts GroupMembers
	 *
	 * @param int $groupId
	 * @return integer
	 */
	public function findById($groupId,$user_id)
	{
		return $this->createQueryBuilder('um')
		->where('um.neighbor = :neighbor')
		->setParameter('neighbor', $user_id)
		->andWhere('um.current = :current')
		->setParameter('current', $groupId)
		->getQuery()
		->getOneOrNullResult();
	}
	
	public function findAllById($groupId)
	{
		return $this->createQueryBuilder('um')
		->where('um.current = :current')
		->setParameter('current', $groupId)
		->getQuery()
		->getResult();
	}
	
	public function findAllAdministrators($groupId)
	{
		return $this->createQueryBuilder('um')
		->where('um.current = :current')
		->setParameter('current', $groupId)
		->andWhere('um.admin = :admin')
		->setParameter('admin', true)
		->getQuery()
		->getResult();
	}
        
        public function findMemberByGroupId($groupId,$user_id)
	{
		return $this->createQueryBuilder('um')
		->where('um.neighbor = :neighbor')
		->setParameter('neighbor', $user_id)
		->andWhere('um.current = :id')
		->setParameter('id', $groupId)
		->getQuery()
		->getOneOrNullResult();
	}
        public function removeAllById($groupId)
        {
            return $this->createQueryBuilder('um')
                    ->delete()
                    ->where('um.current = :groupId')
                    ->setParameter('groupId', $groupId)
                    ->getQuery()
                    ->getResult();
        }
}
