<?php

namespace Fenchy\RegularUserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NeighborhoodMsgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NeighborhoodMsgRepository extends EntityRepository
{
    public function getAllData()
    {
        $q = $this->createQueryBuilder('nm');
        return $q->select('nm')
                 ->orderBy('nm.created_at', 'DESC')
                 ->getQuery()
                 ->getResult();
    }
    
    public function findFullDetailed($id) {
        
        return $this->getDetailedQuery()
                ->where('nm.id = :id')
                ->setParameter('id', $id)
                ->getQuery()
                ->getOneOrNullResult();
    }
    
    
    public function findFullDetailedWithSlug($slug) {
        
        return $this->createQueryBuilder('nm')
                ->select('nm')
                ->where('nm.slug = :slug')
                ->setParameter('slug', $slug)
                ->getQuery()
                ->getOneOrNullResult();
    }
    
    public function getNeighbourhoodMsgRequests($user) {
        
        return $this->createQueryBuilder('nm')
                ->select('nm')
                ->where('nm.user = :user')
                ->setParameter('user', $user)
                ->orderBy('nm.created_at', 'DESC')
                ->getQuery()
                ->getResult();
    }
    
    public function searchNeighborMsg($searchWord=null,$when=null) {
        
        if($when){
         $date = explode('to',$when);
    	 $startdate = date('Y-m-d H:i:s',$date[0]);
    	 $enddate = date('Y-m-d H:i:s',$date[1]);
        }	 
        if($searchWord!=null && $when==null)
        {//echo "@";
            return $this->createQueryBuilder('nm')
                ->select('nm')
                ->andWhere('LOWER(nm.title) like :title')
                ->orWhere('LOWER(nm.content) like :title')
                ->setParameter(':title',strtolower('%' . $searchWord . '%'))
                ->orderBy('nm.created_at', 'DESC')
                ->getQuery()
                ->getResult();
        }
        else if($searchWord==null && $when != null)
        {//echo "@@";
           
                return $this->createQueryBuilder('nm')
                ->select('nm')
                ->andWhere('nm.created_at >= :start AND nm.created_at <= :end ' )
	        ->setParameter('start', $startdate)
	        ->setParameter('end', $enddate)
                ->orderBy('nm.created_at', 'DESC')
                ->getQuery()
                ->getResult();
        }
        else
        {//echo "@@@";
            return $this->createQueryBuilder('nm')
                ->select('nm')
                ->andWhere('LOWER(nm.title) like :title')
                ->orWhere('LOWER(nm.content) like :title')
                ->setParameter(':title',strtolower('%' . $searchWord . '%'))
                ->orderBy('nm.created_at', 'DESC')
                ->getQuery()
                ->getResult();
            
            
        }
            
    }
}
